backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "issues"
    label: "Say覺lar"
    files:
      - name: "issues"
        label: "Say覺lar"
        file: "data/issues.json"
        format: "json"
        fields:
          - label: "Say覺lar"
            name: "items"
            widget: "list"
            fields:
              - { label: "Say覺 No", name: "number", widget: "number" }
              - { label: "Kapak", name: "image", widget: "image" }
              - { label: "Shopier Link", name: "shopier_url", widget: "string" }
